'use strict';
module.exports = {
  IMPORTDIC: {
    '客户名称': 'company_name',
    '用户类型': 'company_type',
    '用户行业': 'company_industry',
    '区域': 'company_region',
    '省': 'company_province',
    '市': 'company_city',
    '区县': 'company_country',
    '地址': 'company_address',
    '序列号': 'order_sn',
    '销售': 'order_sales',
    '合同名称': 'order_name',
    '订单数量': 'order_number',
    '到期后授权': 'order_afterAuthNum',
    '用户数预估': 'order_prediction',
    '授权类型': 'order_type',
    '授权范围': 'order_area',
    '授权到期时间': 'authorization_date',
    '授权年限': 'authorization_years',
    '服务到期时间': 'service_date',
    '服务年限': 'length_of_service',
  },
};
